/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ng4LoadingSpinner.module';
import * as i2 from './ng4LoadingSpinner.service';
export const Ng4LoadingSpinnerModuleNgFactory:i0.NgModuleFactory<i1.Ng4LoadingSpinnerModule> = i0.ɵcmf(i1.Ng4LoadingSpinnerModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.Ng4LoadingSpinnerService,i2.Ng4LoadingSpinnerService,([] as any[])),i0.ɵmpd(512,
          i1.Ng4LoadingSpinnerModule,i1.Ng4LoadingSpinnerModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYW1pdC5tYWhpZGEvRGVza3RvcC90ZXN0L25wbU1vZHVsZS9saWIvbmc0TG9hZGluZ1NwaW5uZXIvbmc0TG9hZGluZ1NwaW5uZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2FtaXQubWFoaWRhL0Rlc2t0b3AvdGVzdC9ucG1Nb2R1bGUvbGliL25nNExvYWRpbmdTcGlubmVyL25nNExvYWRpbmdTcGlubmVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
