/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng4LoadingSpinner.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng4LoadingSpinner.component';
import * as i3 from './ng4LoadingSpinner.service';
const styles_Ng4LoadingSpinnerComponent:any[] = [i0.styles];
export const RenderType_Ng4LoadingSpinnerComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_Ng4LoadingSpinnerComponent,data:{}});
export function View_Ng4LoadingSpinnerComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),8,'div',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          5,'div',[['class','la-ball-clip-rotate-multiple la-3x'],['style','color: #64d6e2']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),0,'div',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    var _co:i2.Ng4LoadingSpinnerComponent = _v.component;
    const currVal_0:any = (_co.showSpinner? 'hidden spinner': 'visible spinner');
    _ck(_v,0,0,currVal_0);
  });
}
export function View_Ng4LoadingSpinnerComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-spinner',
      ([] as any[]),(null as any),(null as any),(null as any),View_Ng4LoadingSpinnerComponent_0,
      RenderType_Ng4LoadingSpinnerComponent)),i1.ɵdid(245760,(null as any),0,i2.Ng4LoadingSpinnerComponent,
      [i3.Ng4LoadingSpinnerService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const Ng4LoadingSpinnerComponentNgFactory:i1.ComponentFactory<i2.Ng4LoadingSpinnerComponent> = i1.ɵccf('app-spinner',
    i2.Ng4LoadingSpinnerComponent,View_Ng4LoadingSpinnerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYW1pdC5tYWhpZGEvRGVza3RvcC90ZXN0L25wbU1vZHVsZS9saWIvbmc0TG9hZGluZ1NwaW5uZXIvbmc0TG9hZGluZ1NwaW5uZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2FtaXQubWFoaWRhL0Rlc2t0b3AvdGVzdC9ucG1Nb2R1bGUvbGliL25nNExvYWRpbmdTcGlubmVyL25nNExvYWRpbmdTcGlubmVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2FtaXQubWFoaWRhL0Rlc2t0b3AvdGVzdC9ucG1Nb2R1bGUvbGliL25nNExvYWRpbmdTcGlubmVyL25nNExvYWRpbmdTcGlubmVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvYW1pdC5tYWhpZGEvRGVza3RvcC90ZXN0L25wbU1vZHVsZS9saWIvbmc0TG9hZGluZ1NwaW5uZXIvbmc0TG9hZGluZ1NwaW5uZXIuY29tcG9uZW50LnRzLk5nNExvYWRpbmdTcGlubmVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBbY2xhc3NdPVwic2hvd1NwaW5uZXIgPyAnaGlkZGVuIHNwaW5uZXInIDogJ3Zpc2libGUgc3Bpbm5lcidcIj5cbiAgPGRpdiBzdHlsZT1cImNvbG9yOiAjNjRkNmUyXCIgY2xhc3M9XCJsYS1iYWxsLWNsaXAtcm90YXRlLW11bHRpcGxlIGxhLTN4XCI+XG4gICAgPGRpdj48L2Rpdj5cbiAgICA8ZGl2PjwvZGl2PlxuICA8L2Rpdj5cbjwvZGl2PiIsIjxhcHAtc3Bpbm5lcj48L2FwcC1zcGlubmVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFrRSx5Q0FDaEU7VUFBQTtVQUFBO01BQXVFLDJDQUNyRTtVQUFBO1VBQUEsZ0JBQVcsMkNBQ1g7VUFBQTtVQUFBLDRDQUFXO1VBQUEsV0FDUDs7SUFKSDtJQUFMLFdBQUssU0FBTDs7OztvQkNBQTtNQUFBOzJDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
