/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/Ng4LoadingSpinner';
import * as i2 from './spinner/spinner.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '../../src/spinner/spinner.service';
export const Ng4LoadingSpinnerNgFactory:i0.NgModuleFactory<i1.Ng4LoadingSpinner> = i0.ɵcmf(i1.Ng4LoadingSpinner,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SpinnerComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,
              i4.SpinnerService,i1.spinnerServiceFactory,([] as any[])),i0.ɵmpd(512,
              i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i1.Ng4LoadingSpinner,
              i1.Ng4LoadingSpinner,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovYW1pdC9teU5vZGVNb2R1bGVzL2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvTmc0TG9hZGluZ1NwaW5uZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovYW1pdC9teU5vZGVNb2R1bGVzL2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvTmc0TG9hZGluZ1NwaW5uZXIudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
