/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './ng4LoadingSpinner.component.css.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './ng4LoadingSpinner.component';
import * as i3 from './ng4LoadingSpinner.service';
const styles_Ng4LoadingSpinnerComponent:any[] = [i0.styles];
export const RenderType_Ng4LoadingSpinnerComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:1,
    styles:styles_Ng4LoadingSpinnerComponent,data:{}});
export function View_Ng4LoadingSpinnerComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),
      [[8,'className',0],[8,'innerHTML',1]],(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['    \n'])),(_l()(),i1.ɵted((null as any),
      ['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),[' ',' '])),(_l()(),i1.ɵted((null as any),['\n\n\n']))],
      (null as any),(_ck,_v) => {
        var _co:i2.Ng4LoadingSpinnerComponent = _v.component;
        const currVal_0:any = (_co.showSpinner? 'visible spinner center': 'hidden spinner center');
        const currVal_1:any = _co._template;
        _ck(_v,0,0,currVal_0,currVal_1);
        const currVal_2:any = (_co.showSpinner? 'visible loading-text': 'hidden loading-text');
        _ck(_v,3,0,currVal_2);
        const currVal_3:any = _co._loadingText;
        _ck(_v,4,0,currVal_3);
      });
}
export function View_Ng4LoadingSpinnerComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-spinner',
      ([] as any[]),(null as any),(null as any),(null as any),View_Ng4LoadingSpinnerComponent_0,
      RenderType_Ng4LoadingSpinnerComponent)),i1.ɵdid(245760,(null as any),0,i2.Ng4LoadingSpinnerComponent,
      [i3.Ng4LoadingSpinnerService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const Ng4LoadingSpinnerComponentNgFactory:i1.ComponentFactory<i2.Ng4LoadingSpinnerComponent> = i1.ɵccf('app-spinner',
    i2.Ng4LoadingSpinnerComponent,View_Ng4LoadingSpinnerComponent_Host_0,{template:'template',
        loadingText:'loadingText',threshold:'threshold'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovYW1pdC9teU5vZGVNb2R1bGVzL25nNExvYWRpbmdTcGlubmVyUmVwby9saWIvbmc0TG9hZGluZ1NwaW5uZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2FtaXQvbXlOb2RlTW9kdWxlcy9uZzRMb2FkaW5nU3Bpbm5lclJlcG8vbGliL25nNExvYWRpbmdTcGlubmVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L2FtaXQvbXlOb2RlTW9kdWxlcy9uZzRMb2FkaW5nU3Bpbm5lclJlcG8vbGliL25nNExvYWRpbmdTcGlubmVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovYW1pdC9teU5vZGVNb2R1bGVzL25nNExvYWRpbmdTcGlubmVyUmVwby9saWIvbmc0TG9hZGluZ1NwaW5uZXIuY29tcG9uZW50LnRzLk5nNExvYWRpbmdTcGlubmVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBbY2xhc3NdPVwic2hvd1NwaW5uZXIgPyAndmlzaWJsZSBzcGlubmVyIGNlbnRlcicgOiAnaGlkZGVuIHNwaW5uZXIgY2VudGVyJ1wiIFtpbm5lckhUTUxdPVwiX3RlbXBsYXRlXCI+ICAgIFxyXG48L2Rpdj5cclxuPGgxIFtjbGFzc109XCJzaG93U3Bpbm5lciA/ICd2aXNpYmxlIGxvYWRpbmctdGV4dCcgOiAnaGlkZGVuIGxvYWRpbmctdGV4dCdcIj4ge3tfbG9hZGluZ1RleHR9fSA8L2gxPlxyXG5cclxuXHJcbiIsIjxhcHAtc3Bpbm5lcj48L2FwcC1zcGlubmVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLGdCQUF3RywyQ0FDbEc7TUFBQSxTQUNOO01BQUE7TUFBMkUsMENBQXVCOzs7UUFGN0Y7UUFBMkU7UUFBaEYsV0FBSyxVQUEyRSxTQUFoRjtRQUVJO1FBQUosV0FBSSxTQUFKO1FBQTJFO1FBQUE7Ozs7b0JDRjNFO01BQUE7MkNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7OyJ9
