/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.spinner[_ngcontent-%COMP%] {\r\n    position: fixed;\r\n    top: 0;\r\n    left: 0;\r\n    padding-top: 20%;\r\n    padding-left: 46%;\r\n    height: 100%;\r\n    width: 100%;\r\n    z-index: 9;\r\n    background: #000;\r\n    opacity: 0.6;\r\n    transition: opacity 0.3s linear;    \r\n}\r\n\r\n.hidden[_ngcontent-%COMP%] {\r\n    visibility: hidden;\r\n    opacity: 0;\r\n    transition: visibility 0s 0.3s, opacity 0.3s linear;\r\n}\r\n\r\n.visible[_ngcontent-%COMP%] {\r\n    visibility: visible;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovYW1pdC9teU5vZGVNb2R1bGVzL2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvc3Bpbm5lci9zcGlubmVyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovYW1pdC9teU5vZGVNb2R1bGVzL2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvc3Bpbm5lci9zcGlubmVyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
