/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './spinner.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../src/spinner/spinner.component';
import * as i3 from '../../../src/spinner/spinner.service';
const styles_SpinnerComponent:any[] = [i0.styles];
export const RenderType_SpinnerComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SpinnerComponent,data:{}});
export function View_SpinnerComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),8,'div',([] as any[]),
      [[8,'className',0]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          5,'div',[['class','la-ball-clip-rotate-multiple la-3x'],['style','color: #64d6e2']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),0,'div',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n']))],(null as any),(_ck,_v) => {
    var _co:i2.SpinnerComponent = _v.component;
    const currVal_0:any = (_co.showSpinner? 'hidden spinner': 'visible spinner');
    _ck(_v,0,0,currVal_0);
  });
}
export function View_SpinnerComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-spinner',
      ([] as any[]),(null as any),(null as any),(null as any),View_SpinnerComponent_0,
      RenderType_SpinnerComponent)),i1.ɵdid(245760,(null as any),0,i2.SpinnerComponent,
      [i3.SpinnerService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SpinnerComponentNgFactory:i1.ComponentFactory<i2.SpinnerComponent> = i1.ɵccf('app-spinner',
    i2.SpinnerComponent,View_SpinnerComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovYW1pdC9teU5vZGVNb2R1bGVzL2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvc3Bpbm5lci9zcGlubmVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9hbWl0L215Tm9kZU1vZHVsZXMvYW5ndWxhci1ucG0tbW9kdWxlLXNlZWQtbWFzdGVyL3NyYy9zcGlubmVyL3NwaW5uZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovYW1pdC9teU5vZGVNb2R1bGVzL2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvc3Bpbm5lci9zcGlubmVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovYW1pdC9teU5vZGVNb2R1bGVzL2FuZ3VsYXItbnBtLW1vZHVsZS1zZWVkLW1hc3Rlci9zcmMvc3Bpbm5lci9zcGlubmVyLmNvbXBvbmVudC50cy5TcGlubmVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBbY2xhc3NdPVwic2hvd1NwaW5uZXIgPyAnaGlkZGVuIHNwaW5uZXInIDogJ3Zpc2libGUgc3Bpbm5lcidcIj5cbiAgPGRpdiBzdHlsZT1cImNvbG9yOiAjNjRkNmUyXCIgY2xhc3M9XCJsYS1iYWxsLWNsaXAtcm90YXRlLW11bHRpcGxlIGxhLTN4XCI+XG4gICAgPGRpdj48L2Rpdj5cbiAgICA8ZGl2PjwvZGl2PlxuICA8L2Rpdj5cbjwvZGl2PiIsIjxhcHAtc3Bpbm5lcj48L2FwcC1zcGlubmVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFrRSx5Q0FDaEU7VUFBQTtVQUFBO01BQXVFLDJDQUNyRTtVQUFBO1VBQUEsZ0JBQVcsMkNBQ1g7VUFBQTtVQUFBLDRDQUFXO1VBQUEsV0FDUDs7SUFKSDtJQUFMLFdBQUssU0FBTDs7OztvQkNBQTtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
